version: 2
updates:
  - package-ecosystem: docker
    directory: "/images/custom-scorecard-tests"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/images/helm-operator"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/images/operator-sdk"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/images/scorecard-test"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/images/scorecard-test-kuttl"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
     interval: daily
  
