# entries is a list of entries to include in
# release notes and/or the migration guide
entries:
  - description: >
      Currently, when setting `overrideValues` in your `watches.yaml`, every entry is logged with its key and its value.
      When working with confidential information such as credentials, logging those information would not be optimal nor
      desirable. Therefore, there should be a way to silence/suppress these values.
      
      This feature introduces the `--suppress-override-values` boolean-flag for the `helm-operator`. When set to true,
      the value of the overrideValues entry is sanitized with this value "****".
      
      This is a simple example of `overrideValues` of the `watches.yaml`
      ```yaml
      overrideValues:
        x: y
      ```
      
      The default-value of `--suppress-override-values` is `false` so therefore we would get this warning logged:
      `Chart value x overridden to y by operator's watches.yaml`

      When setting `--suppress-override-values` `true` the warning will be logged in the following manner:
      `Chart value x overridden to **** by operator's watches.yaml`

    # kind is one of:
    # - addition
    # - change
    # - deprecation
    # - removal
    # - bugfix
    kind: "change"

    # Is this a breaking change?
    breaking: false

    # NOTE: ONLY USE `pull_request_override` WHEN ADDING THIS
    # FILE FOR A PREVIOUSLY MERGED PULL_REQUEST!
    #
    # The generator auto-detects the PR number from the commit
    # message in which this file was originally added.
    #
    # What is the pull request number (without the "#")?
    # pull_request_override: 0