baseURL = "/"
languageCode = "en-us"
title = "Operator SDK"

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Ignore drafts
ignoreFiles = ["docs/kubebuilder"]

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
# [permalinks]
# blog = "/:section/:year/:month/:day/:slug/"

## Configuration for Goldmark markdown parser: https://github.com/yuin/goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# [services]
# [services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration
[languages]
[languages.en]
description = "Go, Ansible, or Helm SDK to simplify the implementation of the operator pattern"
languageName ="English"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]
copyright = "The Operator SDK Authors"
# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/operator-framework/operator-sdk"

# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "website"



# Enable Algolia DocSearch
algolia_docsearch = true

# Update archived_version to true when this version is no longer supported. `version` is only used by the archived banner.
version = "FIXME_when_archived"
archived_version = false
url_latest_version = "https://sdk.operatorframework.io"

[[params.versions]]
  version = "master"
  url = "https://master.sdk.operatorframework.io"
  ##LATEST_RELEASE_KUBE_VERSION##
  kube_version = "1.26.0"
  ##LATEST_RELEASE_CLIENT_GO_VERSION##
  client_go_version = "v0.26.2"

[[params.versions]]
  version = "Latest Release"
  url = "https://sdk.operatorframework.io"
  ##LATEST_RELEASE_KUBE_VERSION##
  kube_version = "1.26.0"
  ##LATEST_RELEASE_CLIENT_GO_VERSION##
  client_go_version = "v0.26.2"

##RELEASE_ADDME##

[[params.versions]]
  version = "v1.29"
  url = "https://v1-29-x.sdk.operatorframework.io"
  kube_version = "1.26.0"
  client_go_version = "v0.26.2"

[[params.versions]]
  version = "v1.28"
  url = "https://v1-28-x.sdk.operatorframework.io"
  kube_version = "1.26.0"
  client_go_version = "v0.26.2"

[[params.versions]]
  version = "v1.27"
  url = "https://v1-27-x.sdk.operatorframework.io"
  kube_version = "1.25.0"
  client_go_version = "v0.25.3"

[[params.versions]]
  version = "v1.26"
  url = "https://v1-26-x.sdk.operatorframework.io"
  kube_version = "1.25.0"
  client_go_version = "v0.25.3"

[[params.versions]]
  version = "v1.25"
  url = "https://v1-25-x.sdk.operatorframework.io"
  kube_version = "1.25.0"
  client_go_version = "v0.25.3"

[[params.versions]]
  version = "v1.24"
  url = "https://v1-24-x.sdk.operatorframework.io"
  kube_version = "1.24.2"
  client_go_version = "v0.24.2"

[[params.versions]]
  version = "v1.23"
  url = "https://v1-23-x.sdk.operatorframework.io"
  kube_version = "1.24.2"
  client_go_version = "v0.24.2"

[[params.versions]]
  version = "v1.22"
  url = "https://v1-22-x.sdk.operatorframework.io"
  kube_version = "1.24.1"
  client_go_version = "v0.24.0"

[[params.versions]]
  version = "v1.21"
  url = "https://v1-21-x.sdk.operatorframework.io"
  kube_version = "1.23"
  client_go_version = "v0.23.5"

[[params.versions]]
  version = "v1.20"
  url = "https://v1-20-x.sdk.operatorframework.io"
  kube_version = "1.23"
  client_go_version = "v0.23.1"

[[params.versions]]
  version = "v1.19"
  url = "https://v1-19-x.sdk.operatorframework.io"
  kube_version = "1.23"
  client_go_version = "v0.23.1"

[[params.versions]]
  version = "v1.18"
  url = "https://v1-18-x.sdk.operatorframework.io"
  kube_version = "1.21"
  client_go_version = "v0.23.1"

[[params.versions]]
  version = "v1.17"
  url = "https://v1-17-x.sdk.operatorframework.io"
  kube_version = "1.21"
  client_go_version = "v0.23.1"

[[params.versions]]
  version = "v1.16"
  url = "https://v1-16-x.sdk.operatorframework.io"
  kube_version = "1.21"
  client_go_version = "v0.22.2"

[[params.versions]]
  version = "v1.15"
  url = "https://v1-15-x.sdk.operatorframework.io"
  kube_version = "1.21"
  client_go_version = "v0.22.2"

[[params.versions]]
  version = "v1.14"
  url = "https://v1-14-x.sdk.operatorframework.io"
  kube_version = "1.21"
  client_go_version = "v0.22.2"

[[params.versions]]
  version = "v1.13"
  url = "https://v1-13-x.sdk.operatorframework.io"
  kube_version = "1.21"
  client_go_version = "v0.22.1"

[[params.versions]]
  version = "v1.12"
  url = "https://v1-12-x.sdk.operatorframework.io"
  kube_version = "1.21"
  client_go_version = "v0.21.2"

[[params.versions]]
  version = "v1.11"
  url = "https://v1-11-x.sdk.operatorframework.io"
  kube_version = "1.20.2"
  client_go_version = "v0.21.2"

[[params.versions]]
  version = "v1.10"
  url = "https://v1-10-x.sdk.operatorframework.io"
  kube_version = "1.20.2"
  client_go_version = "v0.21.2"

[[params.versions]]
  version = "v1.9"
  url = "https://v1-9-x.sdk.operatorframework.io"
  kube_version = "1.20.2"
  client_go_version = "v0.20.2"

[[params.versions]]
  version = "v1.8"
  url = "https://v1-8-x.sdk.operatorframework.io"
  kube_version = "1.20.2"
  client_go_version = "v0.20.2"

[[params.versions]]
  version = "v1.7"
  url = "https://v1-7-x.sdk.operatorframework.io"
  kube_version = "1.19.4"
  client_go_version = "v0.20.2"

[[params.versions]]
  version = "v1.6"
  url = "https://v1-6-x.sdk.operatorframework.io"
  kube_version = "1.19.4"
  client_go_version = "v0.20.2"

[[params.versions]]
  version = "v1.5"
  url = "https://v1-5-x.sdk.operatorframework.io"
  kube_version = "1.19.4"
  client_go_version = "v0.20.2"

[[params.versions]]
  version = "v1.4"
  url = "https://v1-4-x.sdk.operatorframework.io"
  kube_version = "1.19.4"
  client_go_version = "v0.20.1"

[[params.versions]]
  version = "v1.3"
  url = "https://v1-3-x.sdk.operatorframework.io"
  kube_version = "1.19.4"
  client_go_version = "v0.19.4"

[[params.versions]]
  version = "v1.2"
  url = "https://v1-2-x.sdk.operatorframework.io"
  kube_version = "1.18.8"
  client_go_version = "v0.18.8"

[[params.versions]]
  version = "v1.1"
  url = "https://v1-1-x.sdk.operatorframework.io"
  kube_version = "1.18.2"
  client_go_version = "v0.18.8"

[[params.versions]]
  version = "v1.0"
  url = "https://v1-0-x.sdk.operatorframework.io"
  kube_version = "1.18.2"
  client_go_version = "v0.18.6"

[[params.versions]]
  version = "v0.19"
  url = "https://v0-19-x.sdk.operatorframework.io"
  kube_version = "1.18.2"
  client_go_version = "v12.0.0+incompatible"

[[params.versions]]
  version = "v0.18"
  url = "https://v0-18-x.sdk.operatorframework.io"
  kube_version = "1.18.2"
  client_go_version = "v12.0.0+incompatible"

[[params.versions]]
  version = "v0.17"
  url = "https://github.com/operator-framework/operator-sdk/tree/v0.17.x/doc"
  kube_version = "1.17.2"
  client_go_version = "v12.0.0+incompatible"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/operator-framework/operator-sdk/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/operator-framework/operator-sdk/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.social]]
	name = "Forum"
	url = "https://groups.google.com/forum/#!forum/operator-framework"
	icon = "fas fa-comment"

#[[params.links.social]]
#	name = "twitter"
#	url = "https://example.org/mail"
#	icon = "fab fa-twitter"

#[[params.links.social]]
#	name = "youtube"
#	url = "https://example.org/mail"
#	icon = "fab fa-youtube"

[[params.links.social]]
	name = "github"
	url = "https://github.com/operator-framework/operator-sdk"
	icon = "fab fa-github"

#[[params.links.social]]
#	name = "slack"
#	url = "https://example.org/mail"
#	icon = "fab fa-slack"
