name: deploy-manual

on:
  workflow_dispatch:
    inputs:
      ansible_operator_base_tag:
        description: ansible-operator-base image tag, ex. "6e1b47e6ca7c507b8ecf197a8edcd412dd64d85d"
        required: false
      ansible_operator_base_tag_211:
        description: ansible-operator-2.11-preview-base image tag, ex. "6e1b47e6ca7c507b8ecf197a8edcd412dd64d85d"
        required: false

jobs:
  # Build the ansible-operator-base image.
  ansible-operator-base:
    runs-on: ubuntu-20.04
    environment: deploy
    steps:

    - name: set up qemu
      uses: docker/setup-qemu-action@v1

    - name: set up buildx
      uses: docker/setup-buildx-action@v1

    - name: quay.io login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io

    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # Copied this for 2.11 rather than use a matrix because eventually 2.11 will be default and this will be removed.
    - name: create 2.9-base tag
      id: base_tag_29
      run: |
        set -e
        IMG=quay.io/${{ github.repository_owner }}/ansible-operator-base
        TAG="${{ github.event.inputs.ansible_operator_base_tag }}"
        GIT_COMMIT=$(git rev-parse HEAD)
        if [[ "$TAG" == "" ]]; then
          TAG="$(git branch --show-current)-${GIT_COMMIT}"
        fi
        echo ::set-output name=tag::${IMG}:${TAG}
        echo ::set-output name=git_commit::${GIT_COMMIT}

    - name: create 2.11-base tag
      id: base_tag_211
      run: |
        set -e
        IMG=quay.io/${{ github.repository_owner }}/ansible-operator-2.11-preview-base
        TAG="${{ github.event.inputs.ansible_operator_base_tag_211 }}"
        GIT_COMMIT=$(git rev-parse HEAD)
        if [[ "$TAG" == "" ]]; then
          TAG="$(git branch --show-current)-${GIT_COMMIT}"
        fi
        echo ::set-output name=tag::${IMG}:${TAG}
        echo ::set-output name=git_commit::${GIT_COMMIT}

    - name: build and push ansible 2.9 dep image
      uses: docker/build-push-action@v3
      with:
        file: ./images/ansible-operator/base.Dockerfile
        context: ./images/ansible-operator
        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: ${{ steps.base_tag_29.outputs.tag }}
        build-args: |
          GIT_COMMIT=${{ steps.base_tag_29.outputs.git_commit }}

    - name: build and push ansible 2.11 dep image
      uses: docker/build-push-action@v3
      with:
        file: ./images/ansible-operator-2.11-preview/base.Dockerfile
        context: ./images/ansible-operator-2.11-preview
        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: ${{ steps.base_tag_211.outputs.tag }}
        build-args: |
          GIT_COMMIT=${{ steps.base_tag_211.outputs.git_commit }}

    # This change will be staged and committed in the PR pushed below.
    # The script below will fail if no change was made.
    - name: update base of ansible-operator 2.9
      id: update_29
      run: |
        set -ex
        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-base:.+|FROM ${{ steps.base_tag_29.outputs.tag }}|g' images/ansible-operator/Dockerfile
        git diff --exit-code --quiet && echo "Failed to update images/ansible-operator/Dockerfile" && exit 1
        REF="${{ github.event.ref }}"
        echo ::set-output name=branch_name::"${REF##*/}"

    - name: create PR for ansible-operator 2.9 Dockerfile
      uses: peter-evans/create-pull-request@v3
      with:
        title: "[${{ steps.update_29.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.base_tag_29.outputs.tag }}"
        commit-message: |
          [${{ steps.update_29.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.base_tag_29.outputs.tag }}

          Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        body: "New ansible-operator-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        delete-branch: true
        branch-suffix: short-commit-hash

    # This change will be staged and committed in the PR pushed below.
    # The script below will fail if no change was made.
    - name: update base of ansible-operator-2.11-preview
      id: update_211
      run: |
        set -ex
        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-2.11-preview-base:.+|FROM ${{ steps.base_tag_211.outputs.tag }}|g' images/ansible-operator-2.11-preview/Dockerfile
        git diff --exit-code --quiet && echo "Failed to update images/ansible-operator-11-preview-base/Dockerfile" && exit 1
        REF="${{ github.event.ref }}"
        echo ::set-output name=branch_name::"${REF##*/}"

    - name: create PR for ansible-operator-2.11-preview Dockerfile
      uses: peter-evans/create-pull-request@v3
      with:
        title: "[${{ steps.update_211.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.base_tag_211.outputs.tag }}"
        commit-message: |
          [${{ steps.update_211.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.base_tag_211.outputs.tag }}

          Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        body: "New ansible-operator-2.11-preview-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        delete-branch: true
        branch-suffix: short-commit-hash
