on:
  issue_comment:
    types: [created]

jobs:
  rerun_tests:
    name: rerun_pr_tests
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-22.04
    steps:
    - uses: operator-framework/rerun-actions@v0.4.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        comment_id: ${{ github.event.comment.id }}
