name: sanity
on:
  pull_request: {}

jobs:
  check_docs_only:
    name: check_docs_only
    runs-on: ubuntu-18.04
    outputs:
      should_skip_tests: ${{ steps.check_docs_only.outputs.skip-tests }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: check_docs_only
      # Since PR's are squashed prior to merging to the branch checked out (default branch),
      # HEAD^ will resolve to the previous point in history.
      run: |
        REF="HEAD^"
        [[ -z "${{ github.base_ref }}" ]] || REF=$(git show-ref ${{ github.base_ref }} | head -1 | cut -d' ' -f2)
        echo "::set-output name=skip-deploy::$(hack/ci/check-doc-only-update.sh $REF)"

  sanity:
    name: sanity
    runs-on: ubuntu-18.04
    needs: check_docs_only
    if: needs.check_docs_only.outputs.should_skip_tests != 'true'
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: sudo rm -rf /usr/local/bin/kustomize
    - run: make test-sanity

  docs:
    name: docs
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - run: make test-docs
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.2
      with:
        max-depth: 1
        config-file: '.github/workflows/markdown-link-check-config.json'
