name: ansible
on:
  pull_request: {}

jobs:
  check_docs_only:
    name: check_docs_only
    runs-on: ubuntu-18.04
    outputs:
      should_skip_tests: ${{ steps.check_docs_only.outputs.skip-tests }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check_docs_only
        run: |
          REPO_MASTER_REF=$(git show-ref ${{ github.base_ref }} | head -1 | cut -d' ' -f2)
          echo "::set-output name=skip-tests::$(hack/ci/check-doc-only-update.sh $REPO_MASTER_REF)"

  e2e:
    name: e2e
    runs-on: ubuntu-18.04
    needs: check_docs_only
    if: needs.check_docs_only.outputs.should_skip_tests != 'true'
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo rm -rf /usr/local/bin/kustomize
      - run: make test-e2e-ansible

  e2e-molecule:
    name: e2e-molecule
    runs-on: ubuntu-18.04
    needs: check_docs_only
    if: needs.check_docs_only.outputs.should_skip_tests != 'true'
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo rm -rf /usr/local/bin/kustomize
      - run: |
          env
          export PATH=/opt/python/3.6.7/bin:${PATH}
          sudo apt-get install python3 python3-pip
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install ansible~=2.9.13
          make test-e2e-ansible-molecule
