name: go
on:
  pull_request: {}

env:
  MEMCACHED_IMAGE: "memcached:1.4.36-alpine"

jobs:
  check_docs_only:
    name: check_docs_only
    runs-on: ubuntu-24.04
    outputs:
      skip: ${{ steps.check_docs_only.outputs.skip }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: check_docs_only
        # Since PR's are squashed prior to merging to the branch checked out (default branch),
        # HEAD^ will resolve to the previous point in history.
        run: |
          REF="HEAD^"
          [[ -z "${{ github.base_ref }}" ]] || REF=$(git show-ref ${{ github.base_ref }} | head -1 | cut -d' ' -f2)
          echo "skip=$(.github/workflows/check-docs-only.sh $REF)" >> $GITHUB_OUTPUT

  e2e:
    name: e2e
    runs-on: ubuntu-24.04
    needs: check_docs_only
    if: needs.check_docs_only.outputs.skip != 'true'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cleanup Unused Disk Space
        run: |
          .github/workflows/clean-unused-disk-space.sh

      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - run: sudo rm -rf /usr/local/bin/kustomize
      - run: make test-e2e-go

  unit:
    name: unit
    runs-on: ubuntu-24.04
    needs: check_docs_only
    if: needs.check_docs_only.outputs.skip != 'true'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cleanup Unused Disk Space
        run: |
          .github/workflows/clean-unused-disk-space.sh

      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - run: make test-unit
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
